// Mock data for Risk Dashboard
// Severities: critical, high, medium, low
// Statuses: draft, open, in-mitigation, accepted-monitored, closed, promoted
// Trends: worsening, stable, improving
// Pillars: Infrastructure, Applications, Data & Analytics, Security, Operations
// RiskTypes: Technical, Resource, Schedule, Budget, Scope, External
// Entry Types: risk, incident
// Confidence: high, medium, low

const RISKS = [
  {
    id: "R-2841",
    title: "Auth service token rotation may break SSO partners",
    desc: "Quarterly rotation against three federated partners scheduled with no canary window. Two partners have not yet acknowledged the cutover plan.",
    type: "risk",
    pillar: "Security",
    riskType: "Technical",
    status: "in-mitigation",
    severity: "critical",
    trend: "worsening",
    buffer: 3,
    bufferDelta: -3,
    confidence: "high",
    owner: "M. Okafor",
    created: "2026-05-12",
    spark: [22, 20, 18, 14, 11, 7, 3],
    pred: true,
  },
  {
    id: "R-2839",
    title: "Lakehouse compaction job overrunning SLA window",
    desc: "Nightly compaction has crept from 41 min to 68 min over 14 days. Approaching the 75 min downstream cutoff for finance close.",
    type: "risk",
    pillar: "Data & Analytics",
    riskType: "Technical",
    status: "open",
    severity: "critical",
    trend: "worsening",
    buffer: 5,
    bufferDelta: -2,
    confidence: "high",
    owner: "L. Park",
    created: "2026-05-11",
    spark: [12, 12, 11, 9, 8, 6, 5],
    pred: true,
  },
  {
    id: "I-1192",
    title: "Payments gateway 4xx spike during EU peak",
    desc: "Realized incident: 0.8% to 4.2% 4xx rate from 18:20–18:55 UTC on the EU payments gateway. Mitigation in flight with vendor.",
    type: "incident",
    pillar: "Applications",
    riskType: "Technical",
    status: "in-mitigation",
    severity: "high",
    trend: "improving",
    buffer: 9,
    bufferDelta: 2,
    confidence: "high",
    owner: "S. Iyer",
    created: "2026-05-13",
    spark: [4, 5, 7, 9, 8, 9, 9],
  },
  {
    id: "R-2836",
    title: "Q3 cloud commit short by ~$184k at current burn",
    desc: "GPU pool burn pacing 18% above the committed envelope. Reservation true-up window closes June 14.",
    type: "risk",
    pillar: "Infrastructure",
    riskType: "Budget",
    status: "open",
    severity: "high",
    trend: "worsening",
    buffer: 11,
    bufferDelta: -1,
    confidence: "medium",
    owner: "D. Hassan",
    created: "2026-05-09",
    spark: [16, 15, 14, 13, 12, 12, 11],
    pred: true,
  },
  {
    id: "R-2830",
    title: "Senior SRE departure leaves on-call gap in pillar 3",
    desc: "Knowledge concentration on Kafka tooling and runbook ownership. Replacement req opened, no candidate in late-stage.",
    type: "risk",
    pillar: "Operations",
    riskType: "Resource",
    status: "open",
    severity: "high",
    trend: "stable",
    buffer: 21,
    bufferDelta: 0,
    confidence: "high",
    owner: "T. Almeida",
    created: "2026-05-08",
    spark: [22, 21, 21, 21, 21, 21, 21],
  },
  {
    id: "I-1190",
    title: "Customer export job missed nightly window",
    desc: "Daily CSV export to two enterprise tenants completed 3h44m late. Tickets opened by both customers.",
    type: "incident",
    pillar: "Data & Analytics",
    riskType: "Schedule",
    status: "closed",
    severity: "medium",
    trend: "improving",
    buffer: 18,
    bufferDelta: 1,
    confidence: "high",
    owner: "R. Vega",
    created: "2026-05-10",
    spark: [15, 15, 16, 17, 17, 18, 18],
  },
  {
    id: "R-2828",
    title: "GDPR DPA renewal slipping with regional sub-processor",
    desc: "Counterparty has not returned redlines for 11 business days. Legal flagged dependency for the EU region launch.",
    type: "risk",
    pillar: "Security",
    riskType: "External",
    status: "open",
    severity: "medium",
    trend: "worsening",
    buffer: 14,
    bufferDelta: -1,
    confidence: "medium",
    owner: "K. Bauer",
    created: "2026-05-07",
    spark: [18, 17, 17, 16, 15, 14, 14],
  },
  {
    id: "R-2825",
    title: "Mobile checkout scope expanded mid-sprint",
    desc: "Two PM-requested flows added after sprint commit. Engineering capacity unchanged, retro flagged risk to sprint goal.",
    type: "risk",
    pillar: "Applications",
    riskType: "Scope",
    status: "accepted-monitored",
    severity: "medium",
    trend: "stable",
    buffer: 22,
    bufferDelta: 0,
    confidence: "high",
    owner: "P. Nguyen",
    created: "2026-05-06",
    spark: [22, 22, 22, 22, 22, 22, 22],
  },
  {
    id: "R-2822",
    title: "Backup retention drift on legacy NAS tier",
    desc: "Retention policy on the legacy NAS reports 47 days vs 90 day target. Compliance impact is low; remediation queued.",
    type: "risk",
    pillar: "Infrastructure",
    riskType: "Technical",
    status: "accepted-monitored",
    severity: "low",
    trend: "stable",
    buffer: 34,
    bufferDelta: 0,
    confidence: "low",
    owner: "—",
    created: "2026-05-04",
    spark: [34, 34, 34, 34, 34, 34, 34],
    orphaned: true,
  },
  {
    id: "I-1188",
    title: "Doc portal search returning stale results",
    desc: "Indexer not picking up new doc revisions for ~6h after publish. User-visible but workaround in place.",
    type: "incident",
    pillar: "Applications",
    riskType: "Technical",
    status: "closed",
    severity: "low",
    trend: "improving",
    buffer: 40,
    bufferDelta: 2,
    confidence: "medium",
    owner: "J. Cole",
    created: "2026-05-03",
    spark: [38, 38, 39, 39, 40, 40, 40],
  },
];

const APPROVALS = [
  {
    id: "AP-441",
    name: "Accept Risk — R-2825 mobile checkout scope",
    entity: "Accept Risk",
    severity: "medium",
    age: 3,
    requester: "P. Nguyen",
    note: "Sprint owner requests acceptance through end of cycle.",
  },
  {
    id: "AP-438",
    name: "Promote Incident — I-1192 to post-mortem",
    entity: "Incident",
    severity: "high",
    age: 1,
    requester: "S. Iyer",
    note: "Mitigation closing; PIR template attached.",
  },
  {
    id: "AP-435",
    name: "New Risk — Vendor consolidation roadmap",
    entity: "Risk",
    severity: "medium",
    age: 4,
    requester: "K. Bauer",
    note: "Drafted with three impacted pillars tagged.",
  },
];

// Severity trend over last 7 days (counts per day, for overview sparklines)
const SEVERITY_TRENDS = {
  critical: [1, 1, 1, 2, 2, 2, 2],
  high:     [3, 3, 2, 2, 2, 2, 2],
  medium:   [4, 4, 3, 3, 3, 2, 2],
  low:      [2, 2, 2, 2, 2, 2, 2],
};

// Milestone confidence heat — 6 pillars × 7 days, value 0..3 (0 = healthy)
const PILLARS = ["Infrastructure", "Applications", "Data & Analytics", "Security", "Operations"];
const HEAT = [
  // each row = pillar, each col = day (oldest -> today)
  [0, 0, 1, 1, 2, 2, 2], // Infrastructure
  [1, 1, 2, 2, 2, 3, 3], // Applications
  [0, 1, 1, 2, 2, 3, 3], // Data & Analytics
  [2, 2, 2, 3, 3, 3, 3], // Security
  [0, 0, 0, 1, 1, 1, 1], // Operations
];

window.RISK_DATA = { RISKS, APPROVALS, SEVERITY_TRENDS, PILLARS, HEAT };
